const insults = [
    "If laughter is the best medicine, your face must be curing the world.",
    "You're so ugly, you scared the crap out of the toilet.",
    "Your family tree must be a cactus because everybody on it is a prick.",
    "No I'm not insulting you, I'm describing you.",
    "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
    "If I had a face like yours, I'd sue my parents.",
    "Your birth certificate is an apology letter from the condom factory.",
    "I guess you prove that even god makes mistakes sometimes.",
    "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
    "You're so fake, Barbie is jealous.",
    "I�m jealous of people that don�t know you!",
    "My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you're ugly too.",
    "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "You must have been born on a highway because that's where most accidents happen.",
    "Brains aren't everything. In your case they're nothing.",
    "I don't know what makes you so stupid, but it really works.",
    "I can explain it to you, but I can�t understand it for you.",
    "Roses are red violets are blue, God made me pretty, what happened to you?",
    "Behind every fat woman there is a beautiful woman. No seriously, your in the way.",
    "Calling you an idiot would be an insult to all the stupid people.",
    "You, sir, are an oxygen thief!",
    "Some babies were dropped on their heads but you were clearly thrown at a wall.",
    "Don't like my sarcasm, well I don't like your stupid.",
    "Why don't you go play in traffic.",
    "Please shut your mouth when you�re talking to me.",
    "I'd slap you, but that would be animal abuse.",
    "They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.",
    "Stop trying to be a smart ass, you're just an ass.",
    "The last time I saw something like you, I flushed it.",
    "I'm busy now. Can I ignore you some other time?",
    "You have Diarrhea of the mouth; constipation of the ideas.",
    "If ugly were a crime, you'd get a life sentence.",
    "Your mind is on vacation but your mouth is working overtime.",
    "I can lose weight, but you�ll always be ugly.",
    "Why don't you slip into something more comfortable... like a coma.",
    "Shock me, say something intelligent.",
    "If your gonna be two faced, honey at least make one of them pretty.",
    "Keep rolling your eyes, perhaps you'll find a brain back there.",
    "You are not as bad as people say, you are much, much worse.",
    "I don't know what your problem is, but I'll bet it's hard to pronounce.",
    "You get ten times more girls than me? ten times zero is zero...",
    "There is no vaccine against stupidity.",
    "You're the reason the gene pool needs a lifeguard.",
    "Sure, I've seen people like you before - but I had to pay an admission.",
    "How old are you? - Wait I shouldn't ask, you can't count that high.",
    "Have you been shopping lately? They're selling lives, you should go get one.",
    "You're like Monday mornings, nobody likes you.",
    "Of course I talk like an idiot, how else would you understand me?",
    "All day I thought of you... I was at the zoo.",
    "To make you laugh on Saturday, I need to you joke on Wednesday.",
    "You're so fat, you could sell shade.",
    "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
    "Don't you need a license to be that ugly?",
    "My friend thinks he is smart. He told me an onion is the only food that makes you cry, so I threw a coconut at his face.",
    "Your house is so dirty you have to wipe your feet before you go outside.",
    "If you really spoke your mind, you'd be speechless.",
    "Stupidity is not a crime so you are free to go.",
    "You are so old, when you were a kid rainbows were black and white.",
    "If I told you that I have a piece of dirt in my eye, would you move?",
    "You so dumb, you think Cheerios are doughnut seeds.",
    "So, a thought crossed your mind? Must have been a long and lonely journey.",
    "You are so old, your birth-certificate expired.",
    "Every time I'm next to you, I get a fierce desire to be alone.",
    "You're so dumb that you got hit by a parked car.",
    "Keep talking, someday you'll say something intelligent!",
    "You're so fat, you leave footprints in concrete.",
    "How did you get here? Did someone leave your cage open?",
    "Pardon me, but you've obviously mistaken me for someone who gives a damn.",
    "Wipe your mouth, there's still a tiny bit of bullshit around your lips.",
    "Don't you have a terribly empty feeling - in your skull?",
    "As an outsider, what do you think of the human race?",
    "Just because you have one doesn't mean you have to act like one.",
    "We can always tell when you are lying. Your lips move.",
    "Are you always this stupid or is today a special occasion?",
	"What are you going to do for a face when the baboon wants his butt back?",
	"If you're going to be a smartass, first you have to be smart. Otherwise you're just an ass.",
	"Do you still love nature, despite what it did to you?",
	"You've got less meat in your pants than there is in a vegetarian restaurant.",
	"If I wanted to hear from an asshole, I'd fart.",
	"Out of 100,000 sperm, you were the fastest?",
	"Learn from your parent's mistake... Use birth control.",
	"Your face makes onions cry.",
	"If you were twice as smart, you'd still be stupid.",
	"I'm not saying that I hate you, but I'd unplug your life support machine to charge my mobile.",
	"I wasn't born with enough middle fingers to let you know how I feel about you.",
	"Why don't you slip into something a little more comfortable... Like a coma.",
	"I heard your parents took you to a dog show and you won.",
	"You look like something I'd draw with my left hand.",
	"Your birth certificate is an apology letter from the condom factory.",
	"You're about as useful as a vibrator with no batteries.",
	"Your family tree must be a cactus, because everybody on it's a prick.",
	"You look like a before picture.",
	"You're so fake, Barbie is jealous.",
	"Of course I talk like an idiot... How else would you understand me?",
	"What are you doing here? Did someone leave your cage open?",
	"I'm jealous of all the people that haven't met you.",
	"I could eat a bowl of alphabet soup and crap out a smarter comeback than what you just said.",
	"Oh my God, look at the state of you! Was anyone else hurt in the accident?",
	"I'd love to insult you, but I won't do as well as nature did.",
	"Two wrongs don't make a right. Take your parents, for example.",
	"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
	"Hey dog breath, if I throw a stick will you go away?",
	"Calling you an idiot would be an insult to all stupid people.",
	"You're living proof that evolution can go in reverse.",
	"If I had a face like yours, I'd sue my parents.",
	"Are you always an idiot, or just when I'm around?",
	"I'd give you a slap, but that'd be animal abuse.",
	"You're so ugly, Hello Kitty said goodbye to you.",
	"We all sprang from apes, but you didn't spring far enough.",
	"You're so ugly the only dates you get are on a calendar.",
	"You're the reason they invented double doors.",
	"You're so dumb, I bet your dog teaches you tricks.",
	"If you were on fire and I had water, I'd drink it.",
	"You've got a great face for make up.",
	"If you spoke your mind, you'd be speechless.",
	"If I had a face like yours I'd wish I was blind.",
	"You didn't just fall out of the stupid tree, you were dragged through dumbass forest.",
	"Shut up, you'll never be the man your mother is.",
	"Keep rolling your eyes, maybe you'll find a brain back there.",
	"Maybe if you ate some of that make up you could be pretty on the inside.",
	"Fake hair, fake nails, fake smile. Are you sure you weren't made in China?",
	"I'm glad to see you're not letting your education get in the way of your ignorance.",
	"I'm not saying you're stupid, I'm just saying you've got bad luck when it comes to thinking.",
	"You look like your face caught on fire and someone tried to put it out with a fork.",
	"Mirrors can't talk, and lucky for you they can't laugh either.",
	"There's only one problem with your face... I can see it.",
	"I've seen people like you before, but last time I had to pay an admission.",
	"You're so fat you could sell shade.",
	"How many times do I have to flush to get rid of you?",
	"I'd say you're funny, but looks aren't everything.",
	"I bet your brain feels good as new, seeing that you've never used it.",
	"Whatever's eating at you... Must be suffering horribly.",
	"Behind every fat woman there's a beautiful woman. No seriously, you're in the way.",
	"Do you have to leave so soon? I was just about to poison the tea."
]

module.exports = {
    name: 'insult',
    description: 'Insult someone!',
    execute(message, args) {
        
        var insultResponse = insults[Math.floor(Math.random() * insults.length)];
        let user = message.mentions.users.first();

        if (`${user}`!== 'undefined' ){
            message.channel.send(user + ', ' + `${insultResponse}`);
        }
        else{
            message.reply(`${insultResponse}`)
        } 
    },
};


